name: Deploy juci-assistant

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: folias-juci
  REGION: europe-west1
  SERVICE: juci-assistant
  REPOSITORY: services

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'


      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}


      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev


      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA .


      - name: Push Docker image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA


      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 5